# .github/workflows/manual-run.yml  (example)
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_WEBHOOK_LOG_URL: ${{ secrets.DISCORD_WEBHOOK_LOG_URL }}
      ACTIVE_USER: magical_pomelo_39468
      TZ_USER: Asia/Riyadh
      DRY_RUN: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install -U supabase google-genai requests
      - name: Verify env presence (masked)
        run: |
          python - << 'PY'
          import os
          for k in ['SUPABASE_URL','SUPABASE_KEY','DISCORD_WEBHOOK_URL','ACTIVE_USER','TZ_USER','DRY_RUN']:
              print(f"{k}: {'set' if os.getenv(k) else 'MISSING'}")
          PY
      - name: Run morning
        run: python -m tasks.morning_digest
