name: tick-5m

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: masar-tick
      cancel-in-progress: true
    env:
      PYTHONUNBUFFERED: "1"
      # Secrets
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_WEBHOOK_LOG_URL: ${{ secrets.DISCORD_WEBHOOK_LOG_URL }}
      # Vars (optional; code has defaults)
      TZ_USER: ${{ vars.TZ_USER }}
      DRY_RUN: ${{ vars.DRY_RUN }}
      MORNING_DIGEST_TIME: ${{ vars.MORNING_DIGEST_TIME }}
      END_OF_DAY_TIME: ${{ vars.END_OF_DAY_TIME }}
      PRE_CLASS_OFFSET: ${{ vars.PRE_CLASS_OFFSET }}
      POST_CLASS_GRACE: ${{ vars.POST_CLASS_GRACE }}
      ACTIVE_USER: ${{ vars.ACTIVE_USER }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install supabase requests google-genai; fi
      - name: Tick (pre/post/end-of-day logic)
        run: python tasks/tick.py
